maintainer        'Marcos Sainz'
maintainer_email  'marcos@sainz.com'
license           'MIT'
description       'Uses pivotal-sprout to configure an OSX workstation for software development'
long_description  'Uses pivotal-sprout to configure an OSX workstation for software development'
version           '0.1.0'
supports          'mac_os_x'

depends           'pivotal_workstation'
depends           'sprout-osx-base'
depends           'sprout-osx-apps'
depends           'sprout-osx-settings'
depends           'dmg'
depends           'python'
